export const ADMIN_TOPIC_REQUEST = "ADMIN_TOPIC_REQUEST";
export const ADMIN_TOPIC_SUCCESS = "ADMIN_TOPIC_SUCCESS";
export const ADMIN_TOPIC_FAILURE = "ADMIN_TOPIC_FAILURE";

export const ADD_TOPIC_REQUEST = "ADD_TOPIC_REQUEST";
export const ADD_TOPIC_SUCCESS = "ADD_TOPIC_SUCCESS";
export const ADD_TOPIC_FAILURE = "ADD_TOPIC_FAILURE";

export const EDIT_TOPIC_REQUEST = "EDIT_TOPIC_REQUEST";
export const EDIT_TOPIC_SUCCESS = "EDIT_TOPIC_SUCCESS";
export const EDIT_TOPIC_FAILURE = "EDIT_TOPIC_FAILURE";

export const ADMIN_GET_CONTENT_REQUEST = "ADMIN_GET_CONTENT_REQUEST";
export const ADMIN_GET_CONTENT_SUCCESS = "ADMIN_GET_CONTENT_SUCCESS";
export const ADMIN_GET_CONTENT_FAILURE = "ADMIN_GET_CONTENT_FAILURE";

export const ADMIN_UPDATE_CONTENT_REQUEST = "ADMIN_UPDATE_CONTENT_REQUEST";
export const ADMIN_UPDATE_CONTENT_SUCCESS = "ADMIN_UPDATE_CONTENT_SUCCESS";
export const ADMIN_UPDATE_CONTENT_FAILURE = "ADMIN_UPDATE_CONTENT_FAILURE";
